.TH "/home/christopher/Documents/lsm9ds1/inc Directory Reference" 3 "Fri Jul 12 2019" "Version 0.4.0-alpha" "LSM9DS1 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/christopher/Documents/lsm9ds1/inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlsm9ds1\&.h\fP"
.br
.RI "Functions to access the lsm9ds1\&. "
.ti -1c
.RI "file \fBlsm9ds1_accel\&.h\fP"
.br
.RI "Accelerometer functions and data\&. "
.ti -1c
.RI "file \fBlsm9ds1_bus\&.h\fP"
.br
.RI "SPI and I2C Bus functions and data\&. "
.ti -1c
.RI "file \fBlsm9ds1_error\&.h\fP"
.br
.RI "Error codes returned by lsm9ds1 functions\&. "
.ti -1c
.RI "file \fBlsm9ds1_gyro\&.h\fP"
.br
.RI "Gyroscope functions and data\&. "
.ti -1c
.RI "file \fBlsm9ds1_mag\&.h\fP"
.br
.RI "Magnetometer functions and data\&. "
.ti -1c
.RI "file \fBlsm9ds1_temp\&.h\fP"
.br
.RI "Temperature functions and data\&. "
.in -1c
