.TH "/home/christopher/Documents/lsm9ds1/inc Directory Reference" 3 "Wed Jul 3 2019" "Version 0.1.0-alpha" "LSM9DS1 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/christopher/Documents/lsm9ds1/inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlsm9ds1\&.h\fP"
.br
.RI "Functions to access the lsm9ds1\&. "
.in -1c
