.TH "accelerometer_data" 3 "Thu Aug 1 2019" "Version 0.4.0-alpha" "LSM9DS1 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
accelerometer_data
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int16_t \fBx\fP"
.br
.ti -1c
.RI "int16_t \fBy\fP"
.br
.ti -1c
.RI "int16_t \fBz\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for LSM9DS1 Library from the source code\&.
