.TH "lsm9ds1_mag_settings_t" 3 "Sat Aug 3 2019" "Version 0.4.0-alpha" "LSM9DS1 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsm9ds1_mag_settings_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBmag_resolution\fP"
.br
.ti -1c
.RI "uint8_t \fBtemp_comp_enable\fP"
.br
.ti -1c
.RI "lsm9ds1_mag_xy_op_mode_t \fBxy_op_mode\fP"
.br
.ti -1c
.RI "lsm9ds1_mag_odr_t \fBodr\fP"
.br
.ti -1c
.RI "uint8_t \fBfast_odr_enable\fP"
.br
.ti -1c
.RI "uint8_t \fBself_test_enable\fP"
.br
.ti -1c
.RI "lsm9ds1_mag_gain_t \fBgain\fP"
.br
.ti -1c
.RI "uint8_t \fBreboot\fP"
.br
.ti -1c
.RI "uint8_t \fBreset\fP"
.br
.ti -1c
.RI "uint8_t \fBi2c_disable\fP"
.br
.ti -1c
.RI "uint8_t \fBlow_power_mode\fP"
.br
.ti -1c
.RI "lsm9ds1_mag_spi_mode_t \fBspi_mode\fP"
.br
.ti -1c
.RI "lsm9ds1_mag_op_mode_t \fBop_mode\fP"
.br
.ti -1c
.RI "lsm9ds1_mag_z_op_mode_t \fBz_op_mode\fP"
.br
.ti -1c
.RI "uint8_t \fBlittle_endian_enable\fP"
.br
.ti -1c
.RI "uint8_t \fBfast_read_enable\fP"
.br
.ti -1c
.RI "uint8_t \fBblock_data_update_enable\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for LSM9DS1 Library from the source code\&.
