.TH "lsm9ds1_data_t" 3 "Sat Aug 3 2019" "Version 0.4.0-alpha" "LSM9DS1 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsm9ds1_data_t \- Stores the raw data for each sub device\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lsm9ds1\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBlsm9ds1_temperature_t\fP \fBtemperature\fP"
.br
.ti -1c
.RI "\fBaccelerometer_raw_data_t\fP \fBaccelerometer\fP"
.br
.ti -1c
.RI "\fBmag_raw_data_t\fP \fBmagnetometer\fP"
.br
.ti -1c
.RI "\fBgyro_raw_data_t\fP \fBgyroscope\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores the raw data for each sub device\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for LSM9DS1 Library from the source code\&.
