.TH "lsm9ds1_mag_settings_t" 3 "Wed Jun 26 2019" "Version 0.1.0-alpha" "LSM9DS1 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsm9ds1_mag_settings_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "lsm9ds1_mag_gain_t \fBgain\fP"
.br
.ti -1c
.RI "float \fBmag_mgauss\fP"
.br
.ti -1c
.RI "lsm9ds1_mag_odr_t \fBodr\fP"
.br
.ti -1c
.RI "lsm9ds1_mag_op_mode_t \fBop_mode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for LSM9DS1 Library from the source code\&.
