.TH "lsm9ds1_bus_t" 3 "Fri Jul 12 2019" "Version 0.4.0-alpha" "LSM9DS1 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsm9ds1_bus_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBinitialized\fP"
.br
.ti -1c
.RI "int32_t \fBfd\fP"
.br
.ti -1c
.RI "char \fBdevice\fP [256]"
.br
.ti -1c
.RI "\fBlsm9ds1_spi_t\fP \fBspi\fP"
.br
.ti -1c
.RI "\fBlsm9ds1_i2c_t\fP \fBi2c\fP"
.br
.ti -1c
.RI "\fBlsm9ds1_sub_device_t\fP \fBcurrent_sub_device\fP"
.br
.ti -1c
.RI "\fBlsm9ds1_status_t\fP(* \fBtransfer\fP )(struct \fBlsm9ds1_bus_t\fP *self, lsm9ds1_xfer_t op, uint8_t address, uint8_t tx, uint8_t *rx)"
.br
.ti -1c
.RI "\fBlsm9ds1_status_t\fP(* \fBcs_arbiter\fP )(struct \fBlsm9ds1_bus_t\fP *self)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for LSM9DS1 Library from the source code\&.
