.TH "lsm9ds1_spi_t" 3 "Fri Aug 9 2019" "Version 0.4.0-alpha" "LSM9DS1 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsm9ds1_spi_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBinitialized\fP"
.br
.ti -1c
.RI "char \fBname\fP [256]"
.br
.ti -1c
.RI "int32_t \fBfd\fP"
.br
.ti -1c
.RI "uint8_t \fBaddress\fP"
.br
.ti -1c
.RI "uint8_t \fBtx\fP"
.br
.ti -1c
.RI "uint8_t \fBrx\fP [1]"
.br
.ti -1c
.RI "lsm9ds1_xfer_t \fBop\fP"
.br
.ti -1c
.RI "\fBlsm9ds1_spi_settings_t\fP \fBsettings\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for LSM9DS1 Library from the source code\&.
