.TH "lsm9ds1_spi_settings_t" 3 "Sat Aug 3 2019" "Version 0.4.0-alpha" "LSM9DS1 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsm9ds1_spi_settings_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBmode\fP"
.br
.ti -1c
.RI "uint8_t \fBbits\fP"
.br
.ti -1c
.RI "uint32_t \fBspeed\fP"
.br
.ti -1c
.RI "uint16_t \fBspi_delay\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for LSM9DS1 Library from the source code\&.
