.TH "lsm9ds1_gyro_settings_t" 3 "Wed Jun 26 2019" "Version 0.1.0-alpha" "LSM9DS1 Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lsm9ds1_gyro_settings_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "lsm9ds1_gyro_scale_t \fBscale\fP"
.br
.ti -1c
.RI "float \fBgyro_dps_digit\fP"
.br
.ti -1c
.RI "lsm9ds1_gyro_odr_t \fBodr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for LSM9DS1 Library from the source code\&.
